import ArchiveSection from "@/components/ArchiveSection";
import BecomeTester from "@/components/BecomeTester";
import DetailSection from "@/components/DetailSection";
import Hero from "@/components/Hero";
import OptionSection from "@/components/OptionSection";
import PinSection from "@/components/PinSection";
import StreakSection from "@/components/StreakSection";
import ThemeSection from "@/components/ThemeSection";
// import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>StreakTracker</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* <Navbar></Navbar> */}
      <Hero></Hero>
      <ThemeSection></ThemeSection>
      <StreakSection></StreakSection>
      <PinSection></PinSection>
      <ArchiveSection></ArchiveSection>
      <DetailSection></DetailSection>
      <OptionSection></OptionSection>
      <BecomeTester></BecomeTester>

      {/* <Footer></Footer> */}
    </>
  );
}
